### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla2",
  "year": 1980,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 500000
}

### Update 'approved' property in Report
PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
  "approve": true
}

### Get estimate for vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=1980
